# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn clean install -X -DrepoToken=${{ secrets.COVERALLS_TOKEN }}
      
    - name: Discord Notification
    - uses: sarisia/actions-status-discord@v1
      if: always()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        status: ${{ job.status }}
    - name: Coveralls GitHub Action
  # You may pin to the exact commit or the version.
  # uses: coverallsapp/github-action@8cbef1dea373ebce56de0a14c68d6267baa10b44
    - uses: coverallsapp/github-action@v1.1.2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        # Path to lcov file
        #path-to-lcov: # default is ./coverage/lcov.info
        # Job flag name, e.g. "Unit", "Functional", or "Integration". Will be shown in the Coveralls UI.
        #flag-name: # optional
        # Set to true if you are running parallel jobs, then use "parallel_finished: true" for the last action.
        #parallel: # optional
        # Set to true for the last action when using "parallel: true".
        #parallel-finished: # optional
        # Coveralls Enterprise server (more info: https://enterprise.coveralls.io)
        #coveralls-endpoint: # optional, default is https://coveralls.io
        # The root folder of the project that originally ran the tests
        #base-path: # optional
